import {
  ActivityItem,
  QuickAction,
  ServiceCategory,
} from "@/src/types/tabs.home.types";
export const quickActions: QuickAction[] = [
  {
    id: "1",
    route: "/(tabs)/home/safety",
    icon: "shield-checkmark-outline",
    title: "Safety Reminders",
    subtitle: "Stay safe and informed",
  },
  {
    id: "2",
    route: "/(tabs)/home/trobleshooting",
    icon: "construct-outline",
    title: "Troubleshooting",
    subtitle: "Fix common issues fast",
  },
  {
    id: "3",
    route: "/(tabs)/home/saved-draft",
    icon: "document-text-outline",
    title: "Saved Draft Quotes",
    subtitle: "Get in touch quickly",
  },
  {
    id: "4",
    route: "/(tabs)/quotes/my-quotes",
    icon: "document-outline",
    title: "My Quotes",
    subtitle: "Get in touch quickly",
  },
  {
    id: "5",
    route: "https://www.fourelementselectric.com/elemental-harmony" as any,
    icon: "star-outline",
    title: "Elemental Harmony",
    subtitle:
      "Memberships for electrical system, EV charger, & generator maintenance",
  },
];

export const recentActivity: ActivityItem[] = [
  {
    id: "1",
    icon: "flash-outline",
    title: "EV Charger Quote",
    subtitle: "Submitted 2 days ago",
    badge: "Pending",
    badgeColor: "#F59E0B",
  },
  {
    id: "2",
    icon: "alarm-outline",
    title: "Smoke Detector Check",
    subtitle: "Due in 3 days",
    badge: "Upcoming",
    badgeColor: "#3B82F6",
  },
  {
    id: "3",
    icon: "power-outline",
    title: "GFCI Reset Guide",
    subtitle: "Viewed yesterday",
  },
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "1",
    title: "Service Call",
    description: "Quick repairs and electrical\ntroubleshooting",
    iconName: "construct-outline",
    iconBg: "#E8F8F5",
    iconColor: "#2DC99C",
  },
  {
    id: "2",
    title: "EV Charger Installation",
    description: "Home EV charger setup\nWith safe wiring support",
    iconName: "flash-outline",
    iconBg: "#E8F3FD",
    iconColor: "#4A90D9",
  },
  {
    id: "3",
    title: "Panel Upgrade/Replacement",
    description: "Upgrade your panel\nFor safer, stronger power",
    iconName: "cube-outline",
    iconBg: "#F0EDFB",
    iconColor: "#7B61FF",
  },
  {
    id: "4",
    title: "Remodeling",
    description: "Electrical work for\nHome remodel projects",
    iconName: "hammer-outline",
    iconBg: "#FEF3E8",
    iconColor: "#F5A623",
  },
  {
    id: "5",
    title: "Accessory Building /\nShed Power",
    description: "Power for sheds and\nDetached buildings",
    iconName: "business-outline",
    iconBg: "#F5F5F5",
    iconColor: "#888888",
  },
  {
    id: "6",
    title: "Hot Tub Installation",
    description: "Safe electrical setup For\nhot tubs and swim spas",
    iconName: "water-outline",
    iconBg: "#E8F3FD",
    iconColor: "#4A90D9",
  },
  {
    id: "7",
    title: "Dock Power",
    description: "Power solutions for\nDocks and waterfront use",
    iconName: "power-outline",
    iconBg: "#E8F8F5",
    iconColor: "#2DC99C",
  },
  {
    id: "8",
    title: "Electrical Systems Inspection",
    description: "Inspect your system\nFor safety and issues",
    iconName: "document-text-outline",
    iconBg: "#FDF0F8",
    iconColor: "#C94AA0",
  },
  {
    id: "9",
    title: "Generator Installation",
    description: "Backup power setup\nFor homes and buildings",
    iconName: "battery-charging-outline",
    iconBg: "#F5F5F5",
    iconColor: "#888888",
  },
  {
    id: "10",
    title: "New Construction",
    description: "Electrical work for\nNew build projects",
    iconName: "grid-outline",
    iconBg: "#F5F5F5",
    iconColor: "#888888",
  },
  {
    id: "11",
    title: "Solar Installation",
    description: "Electrical support for\nSolar system projects",
    iconName: "sunny-outline",
    iconBg: "#FEF9E8",
    iconColor: "#F5C623",
  },
  // {
  //   id: "12",
  //   title: "Other Custom Service",
  //   description: "Custom electrical help\nFor unique projects",
  //   iconName: "document-outline",
  //   iconBg: "#F0EDFB",
  //   iconColor: "#7B61FF",
  // },

  // other section Rasel Islam
  {
    id: "12",
    title: "Whole Home Surge Protection",
    description: "Protect your entire electrical system",
    iconName: "shield-checkmark-outline",
    iconBg: "#E8F8F5",
    iconColor: "#2DC99C",
  },
  {
    id: "13",
    title: "Starlink Installation",
    description: "Satellite internet setup",
    iconName: "wifi-outline",
    iconBg: "#E8F3FD",
    iconColor: "#4A90D9",
  },

  {
    id: "14",
    title: "Dedicated Circuit",
    description: "For RV and equipment/tools",
    iconName: "hardware-chip-outline",
    iconBg: "#F0EDFB",
    iconColor: "#7B61FF",
  },
  {
    id: "15",
    title: "Exhaust Fan",
    description: "Kitchen, bathroom, or attic fans",
    iconName: "partly-sunny-outline",
    iconBg: "#FEF3E8",
    iconColor: "#F5A623",
  },
  {
    id: "16",
    title: "Outlets",
    description: "Install or replace electrical outlets",
    iconName: "radio-outline",
    iconBg: "#F5F5F5",
    iconColor: "#888888",
  },
  {
    id: "17",
    title: "Switches",
    description: "Light switches and controls",
    iconName: "toggle-outline",
    iconBg: "#FEF9E8",
    iconColor: "#F5C623",
  },
  {
    id: "18",
    title: "Lighting",
    description: "Interior and exterior lighting",
    iconName: "bulb-outline",
    iconBg: "#FEF9E8",
    iconColor: "#F5C623",
  },
  {
    id: "19",
    title: "Ceiling Fan",
    description: "Interior and exterior ceiling fan",
    iconName: "refresh-outline",
    iconBg: "#E8F3FD",
    iconColor: "#4A90D9",
  },
];
